-- 聊天-已读未读
ALTER TABLE T_ONLINECHAT_MESSAGE ADD COLUMN `IS_READ` INT NOT NULL DEFAULT '0' COMMENT '0-未读,1-已读' AFTER `DELETE_STATUS`;
ALTER TABLE T_OTC_ONLINECHAT_MESSAGE ADD COLUMN `IS_READ` INT NOT NULL DEFAULT '0' COMMENT '0-未读,1-已读' AFTER `DELETE_STATUS`;